version: "3.9"

services:
  mysql_ficticio:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dados123
      MYSQL_DATABASE: catalogo_dados
      MYSQL_USER: catalogo_user
      MYSQL_PASSWORD: catalogo123
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data_ficticio:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  mysql_catalogo:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dados123
      MYSQL_DATABASE: catalogo_dados
      MYSQL_USER: catalogo_user
      MYSQL_PASSWORD: catalogo123
      MYSQL_PORT: 3307
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - mysql_data_catalogo:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data_ficticio:
  mysql_data_catalogo: